### ISSUE TITLE
Error when running client in docker image

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [VIS4ROB-lab/covins#16] opened 2022-04-06 07:21 UTC
Hi;    

I run the following:

In terminal 1: ./run.sh -c
In terminal 2: ./run.sh -s ../covins_comm/config/config_comm.yaml ../covins_backend/config/config_backend.yaml
In terminal 3: ./run.sh -o ../covins_comm/config/config_comm.yaml ../orb_slam3/covins_examples/euroc_examples_mh1

Then in terminal 3, I get this error:

run_copy.sh: 1: run_copy.sh: %YAML:1.0: not found
run_copy.sh: 7: run_copy.sh: sys.port:: not found
run_copy.sh: 8: run_copy.sh: sys.server_ip:: not found
run_copy.sh: 14: run_copy.sh: comm.send_updates:: not found
run_copy.sh: 15: run_copy.sh: comm.data_to_client:: not found
run_copy.sh: 17: run_copy.sh: comm.start_sending_after_kf:: not found
run_copy.sh: 18: run_copy.sh: comm.kf_buffer_withold:: not found
run_copy.sh: 19: run_copy.sh: comm.max_sent_kfs_per_iteration:: not found
run_copy.sh: 20: run_copy.sh: comm.update_window_size:: not found
run_copy.sh: 22: run_copy.sh: comm.to_agent_freq:: not found
run_copy.sh: 24: run_copy.sh: comm.start_drift_estimation_after_kf:: not found
run_copy.sh: 30: run_copy.sh: orb.activate_visualization:: not found
run_copy.sh: 31: run_copy.sh: orb.imu_stamp_max_diff:: not found

I used Docker installation

**Comment by ThomasZiegler** [comment] 2022-04-20 14:13
Hi
The `./run.sh -o` requires three parameters (`COMM_CONFIG`, `RUN_FILE`, and  `DATASET_FOLDER`). From the example you give above you are missing the `DATASET_FOLDER` (i.e. the path to the euroc data). Do you get the same error when you add the missing parameter?

**Comment by urbste** [comment] 2022-04-28 11:53
Even if you provide the three parameters you will get the error:
```
run_copy.sh: 6: run_copy.sh: ./../Examples/Monocular-Inertial/mono_inertial_euroc: not found
```
The problem is that the path in the shell scripts is wrong I guess.
If you replace all ``` ./../Examples ```with ``` ./Examples ``` it will work.
Either that or one needs to correct the docker/run.sh and cd into the correct folder.

**Comment by patriksc** [comment] 2022-05-20 17:49
Hello @urbste , thanks for the feedback. You are right, the path in the run.sh needs to be corrected - I'll push a fix in the next days. Thanks for pointing this out!

**Comment by patriksc** [comment] 2022-05-23 17:13
@urbste I just pushed an update for the `run.sh` file. It works fine locally on my machine - if you have a moment to verify it works on your side as well, that would be much appreciated.

**Comment by patriksc** [comment] 2022-07-31 16:43
Problem seems resolved by code update - closing this issue.

**Closed as completed by patriksc** 2022-07-31 16:43 UTC
